version: "2.0"
services:
    web:
        container_name: php5.6
        image: gotechnies/php-5.6-alpine
        ports:
            - "80:80"
            - "443:443"

        volumes:
            - ./:/var/www/html
        restart: always
